/*
 * XpertGroup Prueba
 *
 * Este es el api que se podra consumir desde la aplicacion 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jgonzoe@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Atributo : IEquatable<Atributo>
    { 
        /// <summary>
        /// Tamaño de la matriz
        /// </summary>
        /// <value>Tamaño de la matriz</value>
        [Required]
        [DataMember(Name="N")]
        public long? N { get; set; }

        /// <summary>
        /// Número de operadores
        /// </summary>
        /// <value>Número de operadores</value>
        [Required]
        [DataMember(Name="M")]
        public long? M { get; set; }

        /// <summary>
        /// Gets or Sets Operaciones
        /// </summary>
        [Required]
        [DataMember(Name="operaciones")]
        public List<Operacion> Operaciones { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Atributo {\n");
            sb.Append("  N: ").Append(N).Append("\n");
            sb.Append("  M: ").Append(M).Append("\n");
            sb.Append("  Operaciones: ").Append(Operaciones).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Atributo)obj);
        }

        /// <summary>
        /// Returns true if Atributo instances are equal
        /// </summary>
        /// <param name="other">Instance of Atributo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Atributo other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    N == other.N ||
                    N != null &&
                    N.Equals(other.N)
                ) && 
                (
                    M == other.M ||
                    M != null &&
                    M.Equals(other.M)
                ) && 
                (
                    Operaciones == other.Operaciones ||
                    Operaciones != null &&
                    Operaciones.SequenceEqual(other.Operaciones)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (N != null)
                    hashCode = hashCode * 59 + N.GetHashCode();
                    if (M != null)
                    hashCode = hashCode * 59 + M.GetHashCode();
                    if (Operaciones != null)
                    hashCode = hashCode * 59 + Operaciones.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Atributo left, Atributo right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Atributo left, Atributo right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
